export const customOrder = [
  "Telefon",
  "El",
  "Hemförsäkring",
  "Hyra",
  "LÅN_MoneyGo",
  "LÅN_SEB",
  "Utemat",
  "Mat",
  "Nöje",
  "Resor",
  "Träning",
  "Övrigt",
  "SEB_Enkla",
  "Abonnemang",
  "d",
  "b",
  "e",
];

export const objectPermExpense = {
  Hyra: ["HSB MÖLNDAL EK. FÖR."],
  SEB_Enkla: ["ENKLA VARDAG"],
  Hemförsäkring: ["IF SKADEFÖRS"],
  LÅN_MoneyGo: ["MONEYGO AB"],
  LÅN_SEB: ["LÅNEOMS"],
  El: ["MÖLNDAL ENERGI AB"],
  Telefon: ["TELENOR", "VIMLA"],
  Abonnemang: ["FRISKTANDV", "GOTEBORGS-PO", "UNIONEN", "UNION.AKASSA"],
};

export const objectCustomExpense = {
  Okänd: [
    "1232900371",
    "1233199221",
    "1236218176",
    "1236417380",
    "8662781349",
    "SEATTLE",
    "KFUM REPRIS",
    "GREENSLOPES",
    "GOOGLE  GOOG",
    "BIRMINGHAM"
  ],
  Räkning: ["VISMA FINANCIAL SOLUTION", "QLIRO"],
  Hälsa: [
    "APOTEKET AB",
    "REGIONSERVICE PATIENTFAK",
    "APOTEKSGRUPP",
    "K*FOTBUTIKEN",
  ],
  Nöje: [
    "AMAZONRETAIL",
    "K*SPELBUTIKE",
    "RIOT  AE3N32",
    "RIOT  AE35HZ",
    "HAGABIONS CA",
    "KJELL & CO 1",
    "KJELL & CO 3",
    "BIO ROY",
    "RÖHSSKA MUSE",
  ],
  Present: ["DESIGNTORGET", "AMAZONMKTPLC", "ANTIQVARIA A"],
  Resor: ["VÄSTTRAFIK A", "VASTTRAFIK T"],
  Träning: ["NORDICWELL", "SPORTLIFE M", "FTC MOLNDAL"],
  Övrigt: [
    "SAN FR",
    "DUBLIN",
    "DELABO",
    "VÄSTRA GÖTAL",
    "BJORKAFRIHET",
    "BILLOGRAM",
    "WH GOTEBORG",
    "SAN FRANSICO",
    "SAN FRANCISC",
    "WH GOTEBORG ",
    "GÖTEBORGS UN",
    "K*ETSY.COM",
    "EC STATIONS",
    "AKADEMIBOKHA",
    "KLARNA BANK",
  ],
  Mat: [
    "WILLYS GOTEB",
    "WILLYS HEMMA",
    "WILLY:S AB",
    "LIDL 346",
    "LIDL 326",
    "HEMKOP",
    "HEMKOP GOTEG",
    "HEMKOP TROLL",
    "NYTTIG",
    "4 GOTT AVENY",
    "COOP AVENYN",
    "HEMKOP GOTEB",
    "ICA KVANTUM",
  ],
  Utemat: [
    "FLODAJERNVEG",
    "LILLA TOKYO",
    "KROKSLATTS L",
    "KROKSLATTS S",
    "SALTES RESTA",
    "7-ELEVEN GBG",
    "7ELEVEN GBG",
    "4415193 7-EL",
    "4128113 PRES",
    "4028150 PRES",
    "4428155 PRES",
    "LE SUSHIBAR ",
    "ESPRESSO H 2",
    "K*FOODORA AB",
    "NYTTIG SNABB",
    "PIZZA 4 YOU",
    "ONEFOOD",
    "OAKVILLE",
    "NW GOTEBORG",
    "LE SUSHIBAR",
    "DELABOLE",
    "EDO SUSHI",
    "ESPRESSO HOU",
    "KARAMELLBYRA",
    "MASAKI SUSHI",
    "JAPAN HOUSE",
  ],
};

export const objectKeys = { ...objectPermExpense, ...objectCustomExpense };

export const objectKeysAll = { ...objectPermExpense, ...objectCustomExpense };

export const months = [
  "01",
  "02",
  "03",
  "04",
  "05",
  "06",
  "07",
  "08",
  "09",
  "10",
  "11",
  "12",
];

export const headersTop = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
];
export const headersYear = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "Maj",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Okt",
  "Nov",
  "Dec",
];
